import img1 from '../../img/one.webp';
import img2 from '../../img/two.webp';

export const videoData = [
    {img: img1, title: 'How to Secure API Servers Tutorial - Crash Course on Server Security', channel: 'freeCodeCamp.org', views: "27K views", uploadTime: "9 days ago"},
    {img: img2, title: 'CSS Units 🎯: Are you Using Right CSS unit for making responsive design in websites?', channel: 'Coding Wallah Sir', views: "255 views", uploadTime: "18 hours ago"},
    {img: img1, title: 'How to Secure API Servers Tutorial - Crash Course on Server Security', channel: 'freeCodeCamp.org', views: "27K views", uploadTime: "9 days ago"},
    {img: img2, title: 'CSS Units 🎯: Are you Using Right CSS unit for making responsive design in websites?', channel: 'Coding Wallah Sir', views: "255 views", uploadTime: "18 hours ago"},
    {img: img1, title: 'How to Secure API Servers Tutorial - Crash Course on Server Security', channel: 'freeCodeCamp.org', views: "27K views", uploadTime: "9 days ago"},
    {img: img2, title: 'CSS Units 🎯: Are you Using Right CSS unit for making responsive design in websites?', channel: 'Coding Wallah Sir', views: "255 views", uploadTime: "18 hours ago"},
    {img: img1, title: 'How to Secure API Servers Tutorial - Crash Course on Server Security', channel: 'freeCodeCamp.org', views: "27K views", uploadTime: "9 days ago"},
    {img: img2, title: 'CSS Units 🎯: Are you Using Right CSS unit for making responsive design in websites?', channel: 'Coding Wallah Sir', views: "255 views", uploadTime: "18 hours ago"},
    {img: img1, title: 'How to Secure API Servers Tutorial - Crash Course on Server Security', channel: 'freeCodeCamp.org', views: "27K views", uploadTime: "9 days ago"},
    {img: img2, title: 'CSS Units 🎯: Are you Using Right CSS unit for making responsive design in websites?', channel: 'Coding Wallah Sir', views: "255 views", uploadTime: "18 hours ago"},
    {img: img1, title: 'How to Secure API Servers Tutorial - Crash Course on Server Security', channel: 'freeCodeCamp.org', views: "27K views", uploadTime: "9 days ago"},
    {img: img2, title: 'CSS Units 🎯: Are you Using Right CSS unit for making responsive design in websites?', channel: 'Coding Wallah Sir', views: "255 views", uploadTime: "18 hours ago"},
    {img: img1, title: 'How to Secure API Servers Tutorial - Crash Course on Server Security', channel: 'freeCodeCamp.org', views: "27K views", uploadTime: "9 days ago"},
    {img: img2, title: 'CSS Units 🎯: Are you Using Right CSS unit for making responsive design in websites?', channel: 'Coding Wallah Sir', views: "255 views", uploadTime: "18 hours ago"},
    {img: img1, title: 'How to Secure API Servers Tutorial - Crash Course on Server Security', channel: 'freeCodeCamp.org', views: "27K views", uploadTime: "9 days ago"},
    {img: img2, title: 'CSS Units 🎯: Are you Using Right CSS unit for making responsive design in websites?', channel: 'Coding Wallah Sir', views: "255 views", uploadTime: "18 hours ago"},
    {img: img1, title: 'How to Secure API Servers Tutorial - Crash Course on Server Security', channel: 'freeCodeCamp.org', views: "27K views", uploadTime: "9 days ago"},
    {img: img2, title: 'CSS Units 🎯: Are you Using Right CSS unit for making responsive design in websites?', channel: 'Coding Wallah Sir', views: "255 views", uploadTime: "18 hours ago"},
    {img: img1, title: 'How to Secure API Servers Tutorial - Crash Course on Server Security', channel: 'freeCodeCamp.org', views: "27K views", uploadTime: "9 days ago"},
    {img: img2, title: 'CSS Units 🎯: Are you Using Right CSS unit for making responsive design in websites?', channel: 'Coding Wallah Sir', views: "255 views", uploadTime: "18 hours ago"},
    {img: img1, title: 'How to Secure API Servers Tutorial - Crash Course on Server Security', channel: 'freeCodeCamp.org', views: "27K views", uploadTime: "9 days ago"},
    {img: img2, title: 'CSS Units 🎯: Are you Using Right CSS unit for making responsive design in websites?', channel: 'Coding Wallah Sir', views: "255 views", uploadTime: "18 hours ago"},
    {img: img1, title: 'How to Secure API Servers Tutorial - Crash Course on Server Security', channel: 'freeCodeCamp.org', views: "27K views", uploadTime: "9 days ago"},
    {img: img2, title: 'CSS Units 🎯: Are you Using Right CSS unit for making responsive design in websites?', channel: 'Coding Wallah Sir', views: "255 views", uploadTime: "18 hours ago"},
    {img: img1, title: 'How to Secure API Servers Tutorial - Crash Course on Server Security', channel: 'freeCodeCamp.org', views: "27K views", uploadTime: "9 days ago"},
    {img: img2, title: 'CSS Units 🎯: Are you Using Right CSS unit for making responsive design in websites?', channel: 'Coding Wallah Sir', views: "255 views", uploadTime: "18 hours ago"},
    {img: img1, title: 'How to Secure API Servers Tutorial - Crash Course on Server Security', channel: 'freeCodeCamp.org', views: "27K views", uploadTime: "9 days ago"},
    {img: img2, title: 'CSS Units 🎯: Are you Using Right CSS unit for making responsive design in websites?', channel: 'Coding Wallah Sir', views: "255 views", uploadTime: "18 hours ago"},
    {img: img1, title: 'How to Secure API Servers Tutorial - Crash Course on Server Security', channel: 'freeCodeCamp.org', views: "27K views", uploadTime: "9 days ago"},
    {img: img2, title: 'CSS Units 🎯: Are you Using Right CSS unit for making responsive design in websites?', channel: 'Coding Wallah Sir', views: "255 views", uploadTime: "18 hours ago"},
    {img: img1, title: 'How to Secure API Servers Tutorial - Crash Course on Server Security', channel: 'freeCodeCamp.org', views: "27K views", uploadTime: "9 days ago"},
    {img: img2, title: 'CSS Units 🎯: Are you Using Right CSS unit for making responsive design in websites?', channel: 'Coding Wallah Sir', views: "255 views", uploadTime: "18 hours ago"},
    {img: img1, title: 'How to Secure API Servers Tutorial - Crash Course on Server Security', channel: 'freeCodeCamp.org', views: "27K views", uploadTime: "9 days ago"},
    {img: img2, title: 'CSS Units 🎯: Are you Using Right CSS unit for making responsive design in websites?', channel: 'Coding Wallah Sir', views: "255 views", uploadTime: "18 hours ago"},
    {img: img1, title: 'How to Secure API Servers Tutorial - Crash Course on Server Security', channel: 'freeCodeCamp.org', views: "27K views", uploadTime: "9 days ago"},
    {img: img2, title: 'CSS Units 🎯: Are you Using Right CSS unit for making responsive design in websites?', channel: 'Coding Wallah Sir', views: "255 views", uploadTime: "18 hours ago"},
    {img: img1, title: 'How to Secure API Servers Tutorial - Crash Course on Server Security', channel: 'freeCodeCamp.org', views: "27K views", uploadTime: "9 days ago"},
    {img: img2, title: 'CSS Units 🎯: Are you Using Right CSS unit for making responsive design in websites?', channel: 'Coding Wallah Sir', views: "255 views", uploadTime: "18 hours ago"},
    {img: img1, title: 'How to Secure API Servers Tutorial - Crash Course on Server Security', channel: 'freeCodeCamp.org', views: "27K views", uploadTime: "9 days ago"},
    {img: img2, title: 'CSS Units 🎯: Are you Using Right CSS unit for making responsive design in websites?', channel: 'Coding Wallah Sir', views: "255 views", uploadTime: "18 hours ago"},
    {img: img1, title: 'How to Secure API Servers Tutorial - Crash Course on Server Security', channel: 'freeCodeCamp.org', views: "27K views", uploadTime: "9 days ago"},
    {img: img2, title: 'CSS Units 🎯: Are you Using Right CSS unit for making responsive design in websites?', channel: 'Coding Wallah Sir', views: "255 views", uploadTime: "18 hours ago"},
    {img: img1, title: 'How to Secure API Servers Tutorial - Crash Course on Server Security', channel: 'freeCodeCamp.org', views: "27K views", uploadTime: "9 days ago"},
    {img: img2, title: 'CSS Units 🎯: Are you Using Right CSS unit for making responsive design in websites?', channel: 'Coding Wallah Sir', views: "255 views", uploadTime: "18 hours ago"},
];